
server:
  port: 8120
#  tomcat:
#    max-threads: 256

spring:
  profiles:
    active: prod


formula:
  variable-alias:
    usdcny: usd_in_cny
    # for ccxt okex3
    okex_: okex3_
  access-tokens:
    - ad82c6ae-f7a3-486b-b933-aa19104d8142
    - a867fec8-cadd-4d96-91bc-3f4a85878685
    - 64905f67-0507-4053-a918-9e691252218f
